### ISSUE TITLE
js-weighted-list as npm package

### ISSUE THREAD

**Issue by mattiaerre** [timgilbert/js-weighted-list#3]
Hi @timgilbert I like very much your lib and I would like to understand if you are still working on this or not. I need to have this kind of functionality in a Node.js project and I was wondering if you are interested in having a npm package of it. Let me know if I can help w/ this.
thanks,
-Mattia

**Comment by mattiaerre** [comment]
closing it before this issue turns 1 😜

**Comment by timgilbert** [comment]
Hey, sorry @mattiaerre! I haven't been back to look at this code in quite some time, and it's kind of buggy and not up-to-date for modern JS. Will gladly look at a PR if you have one, but I'm mostly working with ClojureScript these days so this code isn't a priority for me ATM.

**Comment by mattiaerre** [comment]
no problem at all @timgilbert if it was a priority for me I would have pinged you earlier as well 👍 thanks anyway for getting back to me. I was more looking at my outstanding issues and I've found this one at the bottom of my list 😉
